global: 
  scrape_interval: 3s 
 
scrape_configs: 
  - job_name: prometheus 
    static_configs: 
      - targets: ["localhost:9090"] 
  - job_name: bookmarksmanager 
    metrics_path: '/actuator/prometheus'
    static_configs: 
      - targets: ["bookmarksmanager:8080"] 
  - job_name: urlshortner
    metrics_path: '/actuator/prometheus'
    static_configs: 
      - targets: ["urlshortner:8081"] 
  - job_name: jmeter
    metrics_path: '/metrics'
    static_configs: 
      - targets: ["jmeter:9270"] 
